### ISSUE TITLE
Feature request (^)/2 for rationals in SWI-Prolog.

### ISSUE THREAD

**Issue by jburse** [SWI-Prolog/swipl-devel#185]
I like very much that SWI-Prolog provides rationals via the operator rdiv/2. We can do things such as the following:

```
?- X is 1 rdiv 2+1 rdiv 3.
X = 5 rdiv 6.
```
When using rationals we can use all the other operators (+)/2, (-)/2 and (*)/2 in is/2 unchanged. This lead me to the expectation that (^)/2 can also be used unchanged:
```
?- X is (2 rdiv 3)^5.
X = 0.13168724279835387.
```
As can be seen this is not the case. My expectation was:
```
?- X is (2 rdiv 3)^5.
X = 32 rdiv 243.
```
I know that the operator (^)/2 was only recently required the ISO Corr.2. Would it be possibly to extend this operator to also work for exactly rationals?

**Comment by jburse** [comment]
In my prototype I have implemented it as follows:
```
:- override (^)/3.
:- public (^)/3.
^(rational(A,B), Y, rational(H,J)) :- integer(Y), user: (Y>=0), !,
   user: ^(A, Y, H),
   user: ^(B, Y, J).
^(rational(A,B), Y, R) :- integer(Y),
   user: -(Y, K),
   user: ^(A, K, H),
   user: ^(B, K, J),
   integer: /(J, H, R).
```
Means if you have a normalized rational A/B, and is normalized such that B>0 and |gcd(A,B)|=1 than for a positive exponent Y, we can simply compute A^Y/B^Y and don't need to repeat the normalization.

On the other hand if the exponent Y is negative we can use (A/B)^Y = (B^(-Y)/A^(-Y)), but we might need a little normalization again, at least for an invariant denumerator > 0.

**Comment by wouterbeek** [comment]
@jburse Seems that you already have part of the code ready.  Can you contribute this enhancement yourself as per a pull request?

**Comment by jburse** [comment]
I am afraid, I don't know enough of the internals about SWI-Prolog. And it could be also that GMP has something. The important observation, to realize (A rdiv B)^N, we don't need normalize after we took the power. If A and B are co-prime, so will be A^N and B^N.

**Comment by triska** [comment]
Importantly, https://github.com/SWI-Prolog/packages-clpqr/issues/1 may also be related to this&nbsp;issue!

**Comment by JanWielemaker** [comment]
Pushed a4bfaf560ed1ca84bf71f65e4487bb9de69dd3a8, which add support for rationals to ^ and **.
This indeed also fixes the clpq bug.  Closing both.

**Comment by jburse** [comment]
I saw a possibly wrong test case, and hence wrong implementation:

```
X is (2 rdiv 3)^(-5),
	assertion(float(X)),
	assertion(abs(X-7.593750000000002) < 0.0000001).
```

But the result should be simply:

`     X == 243 rdiv 32`

You know rational numbers have a reciprocal, it already works in the current release:

```
Welcome to SWI-Prolog (threaded, 64 bits, version 7.5.8)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.

?- X is 1/(32 rdiv 243).
X = 243 rdiv 32.
```

I also suggest adding this test case, to test the correct sign handling:

```
test(rat, X == -243 rdiv 32) :-
	X is (-2 rdiv 3)^(-5).
```

**Comment by jburse** [comment]
Ok, I see, maybe the idea is to keep up with the ISO definition of (^)/2, respectively with your own behaviour of (^)/2 for integers. Currently I see for SWI-Prolog:
```
Welcome to SWI-Prolog (threaded, 64 bits, version 7.5.8)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.

?- X is 5^(-2).
X = 0.04.
```
With rationals the behaviour would change to, which SWI-Prolog probably wants to avoid:
```
?- X is 5^(-2).
X = 1 rdiv 25
```
In Jekejeke the problem is circumvented, in that rationals only work in the scope of a special overriden is/2 operator. So I am solving the problem in that I have two evaluation contexts, and in the standard evaluation context I even don't allow negative exponent:
```
Jekejeke Prolog 2, Runtime Library 1.2.3
(c) 1985-2017, XLOG Technologies GmbH, Switzerland
?- X is 5^(-2).
Error: Argument should be positive or 0, found -2.
	is/2
```
So in Jekejeke Prolog I currently don't have rationals for the standard is/2, but only in the Computer Algebra System (CAS) module is/2. Only there we can compute with rationals. The below is a preview, note it is in release 1.2.3, I just fixed a bug: 
```
?- use_module(library(groebner/generic)).
% 22 consults and 0 unloads in 1707 ms.
Yes
?- X is 5^(-2).
X is 1/25
```

**Comment by triska** [comment]
I am reopening this issue because it is currently not fully fixed.

I agree with Jan that R^K should yield a **rational** number if R is a rational number and K is an **integer**, also if K is negative.

For example, in SICStus Prolog, we have:

<pre>
| ?- { X = 3/2, Y = X^(-1) }.
X = 3/2,
<b>Y = 2/3 ? ;</b>
no
</pre>

**Comment by jburse** [comment]
But possibly it cannot be solved for the standard is/2, without breaking something, you need also have a solution for 5^(-2) (should it give the float value 0.04 or the rational value 1 rdiv 25?), which I am not 100% sure what the ISO core standard says (my solution is exception for negative exponent):

https://www.complang.tuwien.ac.at/ulrich/iso-prolog/dtc2#pow

Maybe check with Ulrich Neumerkel. You show a CLP(Q) example, right? And there is the context { }/1. I dunno how difficult it is to maybe leave the standard is/2 untouched (for negative exponents) and do something extra for the context { }/1 context. (in the case of negative exponents).

**Comment by triska** [comment]
I hope that floats as we know them today go away rather sooner than&nbsp;later!

For comparison, here is the query with SWI:

<pre>
?- { X = 3/2, Y = X^(-1) }.
<b>false.</b>
</pre>

This means that SWI behaves **different from SICStus** for the important domain of CLP(Q).

I have at least one program where this difference is critical, so I have filed this as https://github.com/SWI-Prolog/packages-clpqr/issues/2.

**Comment by jburse** [comment]
You should blame it on SWI-Prolog kernel, maybe blame it on CLP(Q). I don't have  SICStus Prolog version right now, what does it do outside of CLP(Q), what do you get in SICStus Prolog for:

```
?- X is 5^(-2).

?- X is (2 rdiv 3)^5.      /* I am guessing dunno how rationals look like in SICtus Prolog */
```

**Comment by triska** [comment]
With SICStus, I get:

<pre>
<b>| ?- X is 5^(-2).</b>
! Type error in argument 2 of (is)/2
! expected a float, but found 5
! goal:  _187 is 5^ -2
</pre>

This means that doing something *correct*, namely, yielding:

<pre>
?- X is 5^(-2).
<b>X = 1 rdiv 25.</b>
</pre>

would *not conflict* with something that SICStus computes.

As an aside, it would be slightly odd to now appeal to the ISO standard on this particular issue (of all things!), where it is pretty clear what *should* be computed, and yet completely ignore the standard on much more fundamental&nbsp;issues. Please also take into account that the standard says nothing about rational numbers at&nbsp;all.

With SWI-Prolog, we currently get:

<pre>
?- X is 5^(-2).
<b>X = 0.04.</b>
</pre>

That's quite correct, right? Yes, *quite*:

<pre>
?- X is 5^(-2),
   format("~32f", [X]).
<b>0.04000000000000000083266726846887</b>
</pre>

Behold the pioneering technology from 70 years ago!

**Comment by jburse** [comment]
But try 5^(-2) in SICStus in the CLP(Q) context what do you get? Also floating point error? If the result is different then proof is given that SICStus Prolog uses two different contexts.

P.S.: In this thread you only posted (3/2)^(-1) so far. But the case that is in the intersection with the ISO core standard and the CLP(Q) context is the case where the base argument of the exponentiation is an integer, such as in the example 5^(-2).

**Comment by triska** [comment]
I get, with SICStus:

<pre>
| ?- { X = 5^(-2) }.
<b>X = 1/25 ? ;</b>
no
</pre>

and with SWI:

<pre>
?- { X = 5^(-2) }.
<b>false.</b>
</pre>

Consider now a case with SWI that does not intersect in any way with the core standard:

<pre>
?- X is (1 rdiv 5)^(-1).
<b>X = 5.0.</b>
</pre>

**Expectation**: `X = 5`.

**Comment by jburse** [comment]
Ok now we have proof that SICStus Prolog uses two evaluation contextes, just put side by side:

Standard ISO predicate is/2:
| ?- X is 5^(-2).
! Type error in argument 2 of (is)/2
! expected a float, but found 5
! goal:  _187 is 5^ -2

Evaluation inside CLP(Q):
| ?- { X = 5^(-2) }.
X = 1/25 ? ;
no

What does this tell us? It tells us that we should change a part of CLP(Q), and not is/2.

**Comment by triska** [comment]
Yes, that would be great, thank you!

**Comment by JanWielemaker** [comment]
I think it tells me that we should

  - Make rational numbers a primary citizen rather than a hack using compound terms.
  - Have all operations between integers and rationals return rationals if this is the
    mathematically correct result.   This is not ISO, but advocated by several people
    among whom Richard O'Keefe.

Right now, negative exponentials are supported as in

    ?- X is (1 rdiv 4)^(-2).
    X = 16.

This is compatible with e.g.

    ?- A is 1 rdiv 4/4.
    A = 1 rdiv 16.

But, this is broken because `N rdiv  1` evaluates to an integer, causing float conversion if the 
division does not work.  The below is not desirable:

    ?- A is 4 rdiv 1/3.
    ?- A = 1.3333333333333333.

You can actually force it, as in

    ?- A is rational(4 rdiv 1)/3.
    A = 4 rdiv 3.

The second issue is clp(Q), which in part relies on SWi-Prolog's rational support.  This reliance seems
incomplete, which may be either SWI-Prolog or clp(Q) issues or both.

For now I'll leave it as is, but this should be resolved at some point.

**Comment by jburse** [comment]
Dear All,

Richard O'Keefe idea is already realized, you don't need to do anything anymore, since rdiv/2 is not only a constructor but also an operation, you can do the following, try for yourself with SWI-Prolog:
```
Welcome to SWI-Prolog (threaded, 64 bits, version 7.5.8)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.

?- X is (1 rdiv 4) rdiv (1 rdiv 2).
X = 1 rdiv 2.

?- X is (1 rdiv 2) rdiv (1 rdiv 4).
X = 2.
```
So if you use rdiv/2 instead of (/)/2 you program runs rationals and not floats. I don't see any possility to merge rdiv/2 and (/)/2 into one operator, this is impossible I guess. Now putting side by side the division and the power operator, we could require:

**Datatype Approach:**
datatype            division            power            
float:                  (/)/2                 (**)/2
rational:             (rdiv)/2            (^)/2

When I posted this feature request, I might have had this idea. Meanwhile I have abandoned the above schema in favor of another schema. The schema is based on different contexts and not on different datatypes, the advantage is that I don't need a (rdiv)/2 operator anymore:

**Context Approach:**
context              division            power            
float:                  (/)/2                 (^)/2 /* actually this is cheating it is (**)/2 */
rational:             (/)/2                 (^)/2

So I must appologize, since I issued a datatype feature request, whereby in the end I implemented myself a context feature, much later after I have issued this feature request here. I implemented the context feature via my new library(groebner/generic).

The advantages of the context approach is as follows:
- Typing rdiv/2 is unnatural, its very clumsy, its much easier to type (/)/2.
- Programs can be easily moved from one context into anthor, we do not need to replace (/)/2 by (rdiv)/2.
- The context approach is also followed by CLP(Q), in CLP(Q) we do not need to write { X = Y rdiv Z } instead we write naturally { X = Y / Z }, right?

Hope this helps!

**Comment by jburse** [comment]
If you want to stick to the datatype approach, you could realize this:

Datatype Approach:
============
datatype            division            power            
float:                  (/)/2                 (**)/2
rational:             (rdiv)/2            (^)/2 

But then you would need to remove every float behaviour from (^)/2.

**Comment by JanWielemaker** [comment]
`rdiv` as operation and term was a quick hack.  There is lots of stuff you'd expect to work but that do not. 
For example:

    ?- A is 3 rdiv 4, number(A).
    false.  % YUK!

We can only fix all these if we turn rationals into a proper atomic data type with accompanying syntax.  That is probably not very hard, but requires some restructuring in the basic data representation to accommodate an additional basic type.

The second simple idea is that all basic mathematical functions that have integer or rational arguments and an integer or rational answer returns this exact answer.    So, notably `/` will return a rational number if both arguments are integer/rational.   If you want float division, just write `A is float(X)/Y`.  Combine this with SWI-Prolog's standard order of terms that respects numerical ordering and the world behaves pretty much as you would intuitively expect it to while being logically and mathematically correct.

One issue is that I do not want more dependency on the LGPL GMP library ...

**Comment by jburse** [comment]
Doesn't make any sense to generally change the meaning of (/)/2, since (/)/2 has nothing to do with exact math. I is defined by the ISO core standard as finding a float near the exact value a/b, it is defined as round(a/b). So it is always an approximate operation.

Based on the ISO core definition of (/)/2, a more logical extension would be to ask what the result of rational/rational should be. Analogously to the ISO core standard definition for float and integer arguments, it would be also a float result. Lets check what we have right now:

/* wrong, currently implemented by SWI-Prolog */
?- X is (2 rdiv 3)/(6 rdiv 4).
X = 4 rdiv 9.

Which is wrong. It should give:

/* correct, logical consequence of the ISO core standard definition */
?- X is (2 rdiv 3)/(6 rdiv 4).
X = 0.4444444444444444.

You get the idea. I am saying there are two different operations, an old existing one (/)/2, already defined by ISO core standard, which aim is to return a float approximation. And there is a new one (rdiv)/2 which will return an exact result.

**Comment by JanWielemaker** [comment]
As Richard has argued many times, (ISO) Prolog arithmetic is flawed.  Floats are fine for functions that inherently are about __real__ numbers (in the match sense).   Otherwise they are a poor match for any high level languages and particularly so for a logic based language.   Switching to an approximation should be really the last resort, in particular so because unification is based on strict equivalence.   If you want scruffy arithmetic, just cast one or more of the operands to a float using `float(X)` and all subsequent arithmetic will use floats as we cannot get exact results after having introduced an approximation.

ISO should have demanded unbounded integer and rational number support from the start.  Well, possibly this was asking too much back then, but it should have corrected this error long ago.

**Comment by jburse** [comment]
ut I know that SWI-Prolog wants to do something smart. It also doesn't have the below type invariants, it sometimes returns integer. I don't believe that this smartness is desired or realizable with rationals.

Especially with rationals we run into the problem that every float is a rational. Since a float is mantiassa (an integer) multiplied by base power exponent (exponent positive or negative integer, hence in case of negative integer a rational number):

float = mantissa * base^exponent

So the smartness breaks for rational. You could "automatically" convert every float result into a rational number. So its impossible to do the same automatism, which was done for integers also for ratuional numbers. Thats also why there is an explicit function rationalize:

?- X is pi.
X = 3.141592653589793.

?- X is rationalize(pi).
X = 245850922 rdiv 78256779.

I am pretty sure that Richard O'Keefe would agree with me that this smartness doesn't make any sense any more for rational numbers, and that it has nothing to do with the ISO core standard, but simply that every float number is also a rational number.

**Comment by jburse** [comment]
Since every float number is also a rational number, we could suddently require that all basic opertions are more smart, which is absurd:

?- X is pi*pi
X = 60442675848250084 rdiv 6124123459454841.

The absurdness is that an originally designed approximate datatype, i.e. floats, looses all its approximate operations. There is nothing "scruffy" what ever this should mean, having a set of operations for the following in parallel:
- approximate operations, for example float
- exact operations, for example rational numbers

Both operations are mathematically defined, there is nothing "scruffy" or illogical here. Approximatge operations can be also mathematically defined, and you see a lot of such definitions in the ISO core standard.

**Comment by JanWielemaker** [comment]
Automatic casting **never** turns a float into a rational, as floats are never converted into integers right now.  Only explicit casting does so, where you control the rounding.   All this is not rocket science.

**Comment by jburse** [comment]
Yes, I see, this is probably right. You still preserve sometimes the float type:
```
?- X is 9.0/3.0.
X = 3.0.

?- X is 3.0/9.0.
X = 0.3333333333333333.
```
But the float invariant is broken, so you miss opportunities for compiler optimization:
```
?- X is 9/3. /* why does the result type change? */
X = 3.

?- X is 3/9.
X = 0.3333333333333333.
```
You miss opportunities since you cannot statically determine types.

**Comment by JanWielemaker** [comment]
You use the opportunity that Prolog is a dynamically typed language.   This `issue' will go away if `3/9` becomes a rational as integers are just a pure subset of rationals, while integers are a pure subset of math _real_ numbers, but _not_ of _floats_.

**Comment by jburse** [comment]
This is impossible and sounds a little absurd again. There are also [irrational numbers](https://en.wikipedia.org/wiki/Irrational_number), you cannot represent pi on the computer. You will need some precision. So there will be always floats somewhere, at least if you want to do numerics. And even if you have a symbolic system, somebody might do the following:

?- X is floor(pi*10^n)
X = n-digits of pi

So you will always have numerics somewhere, except if you forbid the floor operation. You know there is an old joke, people in the past have always asked me whether it is right, that we cannot do numerics in Prolog. I always told them, no, there is a datatype float, you can do everything ordinary numerics.

What you can do you can extend the reach of floats and numerics, by for example implementing muliprecission decimals in Prolog. You find this as VPA in MATLAB. I have already implemented such a library in Prolog, here you see how the precision can be increased when dealing with irratonal numbers:

```
Jekejeke Prolog 2, Runtime Library 1.2.2
(c) 1985-2017, XLOG Technologies GmbH, Switzerland

?- X is exp(pi*sqrt(163))-640320^3.
X = 256.0

?- use_module(library(decimal/multi)).
% 7 consults and 0 unloads in 141 ms.
Yes

?- X is mp(exp(pi*sqrt(163))-640320^3,32).
X = 0d743.99999999999711

?- X is mp(exp(pi*sqrt(163))-640320^3,64).
X = 0d743.99999999999925007259719818568887935385633
73653

?- X is mp(exp(pi*sqrt(163))-640320^3,128).
X = 0d743.99999999999925007259719818568887935385633
733699086270753741037821064791011860731295118134618
606450419308389132 
```

**Comment by jburse** [comment]
I don't think the feature was correctly implemented. I get for example
this buggy result:

   ?- X is (13 rdiv 4 - (1 rdiv 2)*(1 rdiv 2))^(-1).
   X = 1 rdiv 3.

   ?- Y is 13 rdiv 4 - (1 rdiv 2)*(1 rdiv 2), X is Y^(-1).
   Y = 3,
   X = 0.3333333333333333.

It would be better if we had two pairs ideally like (/)/2 and rdiv/2, we
a clear definition which one returns float and which one returns rational numbers.

**Comment by jburse** [comment]
I am not sure, maybe (**)/2 and (^)/2 could play this role.
The expected outcome would then be:

We could reserve (**)/2, so that this
operator only returns float:

   ?- X is (13 rdiv 4 - (1 rdiv 2)*(1 rdiv 2))**(-1).
   X = 0.3333333333333333.

   ?- Y is 13 rdiv 4 - (1 rdiv 2)*(1 rdiv 2), X is Y**(-1).
   Y = 3,
   X = 0.3333333333333333.

And (^)/2 would always try rational numbers:

   ?- X is (13 rdiv 4 - (1 rdiv 2)*(1 rdiv 2))^(-1).
   X = 1 rdiv 3.

   ?- Y is 13 rdiv 4 - (1 rdiv 2)*(1 rdiv 2), X is Y^(-1).
   Y = 3,
   X = 1 rdiv 3.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/future-of-support-for-rational-numbers/1779/14

**Comment by jburse** [comment]
I found a further argument to give different roles to (**)/2 and (^)/2.

For example ECLiPSe Prolog gives this result, since it does not
normalize rational numbers to ordinary integers where possible:
```
   ECLiPSe Version 7.0 #52 (x86_64_nt)

   [eclipse 1]: X is 2_1^(-5).
   X = 1_32
   Yes (0.00s cpu)

   [eclipse 2]: X is 2^(-5).
   X = 0.03125
   Yes (0.00s cpu)
```
On the other hand I get:
```
   SWI-Prolog (threaded, 64 bits, version 8.1.22)

   ?- X is 2r1^(-5).
   X = 0.03125. 
```
So from the data type of the argument of (^)/2 it cannot
be seen what to do, and we possibly cannot get a non-float

result like 1r32. Except we would give this role to (**)/2 and
reserve (^)/2 to give rational numbers.
